sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t alexvinitsky/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alexvinitsky/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-east-1-443681844828'
  bucket_path: 'docker-react'
  aws_access_key_id:
   secure: "AKIAWOTL7VZOC5CNSBV7"
  aws_secret_access_key:
   secure: "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"
on:
  branch: master